/**
 * The Notette mark — the same artwork as `static/favicon.svg` and
 * `static/logo.png` — embedded as a 128x128 PNG. Emails attach it and
 * reference it by content ID rather than linking to the site: many clients
 * block remote images by default and none of them render SVG, and the
 * instance's public URL is not always configured.
 *
 * Generated by `scripts/render-logo.mjs`; do not edit by hand.
 */
export const LOGO_CID = 'notette-logo';
export const LOGO_FILENAME = 'notette-logo.png';

const LOGO_PNG_BASE64 =
	'iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAADSUlEQVR42u3cPY6cQBCGYY7AEfoInIIU5NARqbM+ArkD5BPMPSxZ' +
	'HGEuYHkiZMkJge1kJWtspEbqHc8Pw9AL09+70ic5clD10AUFu0mRd0ngmCLvyn//rou8a136Iu+O5FV6rz61q5kJ3Z9Q/3FW5F1T' +
	'5N2Bxj6cg6tltnUAaZF3lqYHx2BdrTcDIHVHFsf6246LegkIjzbf0vjVIdg1ABh3s0ITtpF27g3jnOZXXPWbPQ2q0AB2FHrz2YUC' +
	'QPMjRDC1+XuK+nTZLwWAKz/ik4DmiyO4dbdPAeNIdS8Aw6NedI+I5h4ALHniXBZNAmApVrSxtwCkHP3Rj4L0GoCaIkWf+hIArn7B' +
	'U4DZL34v4APgSx6tL4teAcgoilwyH0BDQeTS+AA4/kXHwLj2pSCaMYn7BQSKoZmS5Y/4UogXP+IviAAAANa/ymvhhCJoBwAAoAgA' +
	'IAAgACAAWD+x/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
	'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8Mx/KHLJn08fe/44pCKAXz//HO2HHzRcEcC3ry/H9+++' +
	'02xFAF8+/6bJqgCY96IAmPfCAJj3wgCY98IAmPeiAJj3wgCY98IAmPfCAJj3ogCY98IAmPfCAJj34gAIAAgACAAIAAgASAAAPYWQ' +
	'TT8AaCmEbFoAAKCrKYRs6gFASSFkUw4ADIWQjRkADDlQDLkMPU9GAA0FkUvjA8goiFwyHwBjQPD4PwVgKYxM7DkAKWthjfWv6/V/' +
	'AFgKiSx//J6fAuAUELr6zwHgXkBk9l8DwAuiSF/8nOv1JQCGURDd0W/uATCkonDRpLrU52sAhuwo3tNnd63HtwCAIOLmTwUwZE8x' +
	'ny77Kb2dCoCTILIrfw4AEETW/DkAxqcDHhG3+ahX3dvPOQDGPQHLom0tecycXs4F4K+NOQ3WvertIz18FMD4AqkGwps3vj59sbMW' +
	'AB+C5cui4F/y2CUaHwKAn8x9dAiGZZrejN/wLZ1QAE5vGEt3ZLUujIvzx/pYn9rVzITuz1+Oygo8iKyFCQAAAABJRU5ErkJggg==';

/** The mark as PNG bytes, for attaching to an outgoing email. */
export function logoPngBuffer(): Buffer {
	return Buffer.from(LOGO_PNG_BASE64, 'base64');
}
