#!/usr/bin/env node
/**
 * Rasterises the Notette mark from `static/favicon.svg` and writes:
 *
 *   static/logo.png                 128x128 PNG of the same artwork
 *   src/lib/server/email/logo.ts    that PNG embedded as base64 for emails
 *
 *   pnpm run logo
 *
 * The geometry below mirrors `static/favicon.svg` (a rounded square plus the
 * speech-bubble path). Keep the two in sync: if the SVG changes, update the
 * constants here and re-run this script.
 */
import { deflateSync } from 'node:zlib';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const SIZE = 128; // rendered at 128px so it stays crisp on high-DPI screens
const VB = 32; // SVG viewBox size
const SS = 4; // supersamples per axis, for antialiased edges
const RADIUS = 8;
const ACCENT = [0x4f, 0x46, 0xe5];
const WHITE = [0xff, 0xff, 0xff];

/** `M9 9 h14 v10 H15 l-5 4 v-4 H9 z` from the SVG, as absolute points. */
const POLY = [
	[9, 9],
	[23, 9],
	[23, 19],
	[15, 19],
	[10, 23],
	[10, 19],
	[9, 19]
];

const scale = SIZE / VB;

function inRoundedRect(x, y) {
	if (x < 0 || y < 0 || x > VB || y > VB) return false;
	const dx = x - Math.min(Math.max(x, RADIUS), VB - RADIUS);
	const dy = y - Math.min(Math.max(y, RADIUS), VB - RADIUS);
	return dx * dx + dy * dy <= RADIUS * RADIUS;
}

function inPolygon(x, y) {
	let inside = false;
	for (let i = 0, j = POLY.length - 1; i < POLY.length; j = i++) {
		const [xi, yi] = POLY[i];
		const [xj, yj] = POLY[j];
		if (yi > y !== yj > y && x < ((xj - xi) * (y - yi)) / (yj - yi) + xi) inside = !inside;
	}
	return inside;
}

/** RGBA scanlines with a zero filter byte per row, ready for deflate. */
function renderRaw() {
	const raw = Buffer.alloc(SIZE * (SIZE * 4 + 1));
	const total = SS * SS;
	for (let py = 0; py < SIZE; py++) {
		const rowStart = py * (SIZE * 4 + 1);
		for (let px = 0; px < SIZE; px++) {
			let cover = 0;
			let bubble = 0;
			for (let sy = 0; sy < SS; sy++) {
				for (let sx = 0; sx < SS; sx++) {
					const x = (px + (sx + 0.5) / SS) / scale;
					const y = (py + (sy + 0.5) / SS) / scale;
					if (!inRoundedRect(x, y)) continue;
					cover++;
					if (inPolygon(x, y)) bubble++;
				}
			}
			const mix = cover ? bubble / cover : 0;
			const o = rowStart + 1 + px * 4;
			for (let c = 0; c < 3; c++) raw[o + c] = Math.round(ACCENT[c] * (1 - mix) + WHITE[c] * mix);
			raw[o + 3] = Math.round((cover / total) * 255);
		}
	}
	return raw;
}

let crcTable = null;
function crc32(buf) {
	if (!crcTable) {
		crcTable = new Int32Array(256);
		for (let n = 0; n < 256; n++) {
			let c = n;
			for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
			crcTable[n] = c;
		}
	}
	let c = -1;
	for (const b of buf) c = crcTable[(c ^ b) & 0xff] ^ (c >>> 8);
	return (c ^ -1) >>> 0;
}

function chunk(type, data) {
	const len = Buffer.alloc(4);
	len.writeUInt32BE(data.length);
	const body = Buffer.concat([Buffer.from(type, 'ascii'), data]);
	const crc = Buffer.alloc(4);
	crc.writeUInt32BE(crc32(body));
	return Buffer.concat([len, body, crc]);
}

function encodePng(raw) {
	const ihdr = Buffer.alloc(13);
	ihdr.writeUInt32BE(SIZE, 0);
	ihdr.writeUInt32BE(SIZE, 4);
	ihdr[8] = 8; // bit depth
	ihdr[9] = 6; // colour type: RGBA
	return Buffer.concat([
		Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
		chunk('IHDR', ihdr),
		chunk('IDAT', deflateSync(raw, { level: 9 })),
		chunk('IEND', Buffer.alloc(0))
	]);
}

function logoModule(png) {
	const lines = png
		.toString('base64')
		.match(/.{1,100}/g)
		.map((line) => `\t'${line}'`)
		.join(' +\n');
	return `/**
 * The Notette mark — the same artwork as \`static/favicon.svg\` and
 * \`static/logo.png\` — embedded as a ${SIZE}x${SIZE} PNG. Emails attach it and
 * reference it by content ID rather than linking to the site: many clients
 * block remote images by default and none of them render SVG, and the
 * instance's public URL is not always configured.
 *
 * Generated by \`scripts/render-logo.mjs\`; do not edit by hand.
 */
export const LOGO_CID = 'notette-logo';
export const LOGO_FILENAME = 'notette-logo.png';

const LOGO_PNG_BASE64 =
${lines};

/** The mark as PNG bytes, for attaching to an outgoing email. */
export function logoPngBuffer(): Buffer {
	return Buffer.from(LOGO_PNG_BASE64, 'base64');
}
`;
}

const png = encodePng(renderRaw());
writeFileSync(join(root, 'static/logo.png'), png);
writeFileSync(join(root, 'src/lib/server/email/logo.ts'), logoModule(png));
console.log(`static/logo.png (${SIZE}x${SIZE}, ${png.length} bytes) and src/lib/server/email/logo.ts written`);
