import {
	boolean,
	index,
	integer,
	jsonb,
	pgEnum,
	pgTable,
	real,
	text,
	timestamp,
	uniqueIndex,
	uuid
} from 'drizzle-orm/pg-core';
import type { DeploymentInfo, ElementRect } from '$lib/shared/types';

export const userRole = pgEnum('user_role', ['owner', 'admin']);
export const sessionKind = pgEnum('session_kind', ['dashboard', 'widget']);
export const feedbackStatus = pgEnum('feedback_status', ['open', 'resolved']);
export const authRequestStatus = pgEnum('auth_request_status', ['pending', 'approved', 'denied']);

const timestamps = {
	createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
	updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow()
};

export const users = pgTable(
	'users',
	{
		id: uuid('id').primaryKey().defaultRandom(),
		email: text('email').notNull(),
		name: text('name').notNull(),
		passwordHash: text('password_hash').notNull(),
		role: userRole('role').notNull().default('admin'),
		...timestamps
	},
	(t) => [uniqueIndex('users_email_idx').on(t.email)]
);

export const projects = pgTable(
	'projects',
	{
		id: uuid('id').primaryKey().defaultRandom(),
		name: text('name').notNull(),
		clientKey: text('client_key').notNull(),
		allowedOrigins: jsonb('allowed_origins').$type<string[]>().notNull().default([]),
		/** Reviewers (unauthenticated visitors) can see existing feedback pins and threads. */
		publicFeedbackVisible: boolean('public_feedback_visible').notNull().default(true),
		/** Reviewers can reply to threads. */
		reviewerRepliesEnabled: boolean('reviewer_replies_enabled').notNull().default(true),
		/** The widget captures a viewport screenshot with each feedback item. */
		screenshotsEnabled: boolean('screenshots_enabled').notNull().default(true),
		feedbackSeq: integer('feedback_seq').notNull().default(0),
		...timestamps
	},
	(t) => [uniqueIndex('projects_client_key_idx').on(t.clientKey)]
);

export const sessions = pgTable(
	'sessions',
	{
		/** SHA-256 hex digest of the raw token. */
		id: text('id').primaryKey(),
		userId: uuid('user_id')
			.notNull()
			.references(() => users.id, { onDelete: 'cascade' }),
		kind: sessionKind('kind').notNull(),
		/** Widget sessions are bound to one project and one host origin. */
		projectId: uuid('project_id').references(() => projects.id, { onDelete: 'cascade' }),
		origin: text('origin'),
		userAgent: text('user_agent'),
		ipAddress: text('ip_address'),
		createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
		lastUsedAt: timestamp('last_used_at', { withTimezone: true }).notNull().defaultNow(),
		expiresAt: timestamp('expires_at', { withTimezone: true }).notNull()
	},
	(t) => [index('sessions_user_idx').on(t.userId), index('sessions_expires_idx').on(t.expiresAt)]
);

export const authRequests = pgTable(
	'auth_requests',
	{
		/** Generated by the widget so the authorize URL can be opened synchronously. */
		id: uuid('id').primaryKey(),
		projectId: uuid('project_id')
			.notNull()
			.references(() => projects.id, { onDelete: 'cascade' }),
		origin: text('origin').notNull(),
		pollSecretHash: text('poll_secret_hash').notNull(),
		status: authRequestStatus('status').notNull().default('pending'),
		/** Raw widget token, present only between approval and pickup by the widget. */
		token: text('token'),
		sessionId: text('session_id').references(() => sessions.id, { onDelete: 'cascade' }),
		approvedById: uuid('approved_by_id').references(() => users.id, { onDelete: 'set null' }),
		createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
		expiresAt: timestamp('expires_at', { withTimezone: true }).notNull()
	},
	(t) => [index('auth_requests_expires_idx').on(t.expiresAt)]
);

export const feedback = pgTable(
	'feedback',
	{
		id: uuid('id').primaryKey().defaultRandom(),
		projectId: uuid('project_id')
			.notNull()
			.references(() => projects.id, { onDelete: 'cascade' }),
		/** Per-project sequential number shown as #12. */
		number: integer('number').notNull(),
		status: feedbackStatus('status').notNull().default('open'),
		body: text('body').notNull(),
		authorName: text('author_name'),
		authorEmail: text('author_email'),
		/** Set when the author was an authenticated admin. */
		userId: uuid('user_id').references(() => users.id, { onDelete: 'set null' }),

		url: text('url').notNull(),
		path: text('path').notNull(),
		pageTitle: text('page_title'),
		viewportWidth: integer('viewport_width'),
		viewportHeight: integer('viewport_height'),
		devicePixelRatio: real('device_pixel_ratio'),
		scrollX: integer('scroll_x'),
		scrollY: integer('scroll_y'),
		/** Click position in page (document) coordinates. */
		clickX: integer('click_x'),
		clickY: integer('click_y'),

		elementSelector: text('element_selector'),
		elementXpath: text('element_xpath'),
		elementTag: text('element_tag'),
		elementText: text('element_text'),
		elementAttributes: jsonb('element_attributes').$type<Record<string, string>>(),
		/** Bounding box of the target element in page coordinates at capture time. */
		elementRect: jsonb('element_rect').$type<ElementRect>(),
		/** Click position relative to the element box (0..1). */
		elementRelX: real('element_rel_x'),
		elementRelY: real('element_rel_y'),

		userAgent: text('user_agent'),
		/** SHA-256 of a one-time token that authorizes the screenshot upload right after creation. */
		uploadTokenHash: text('upload_token_hash'),
		deployment: jsonb('deployment').$type<DeploymentInfo>(),
		metadata: jsonb('metadata').$type<Record<string, unknown>>(),

		resolvedAt: timestamp('resolved_at', { withTimezone: true }),
		resolvedById: uuid('resolved_by_id').references(() => users.id, { onDelete: 'set null' }),
		...timestamps
	},
	(t) => [
		uniqueIndex('feedback_project_number_idx').on(t.projectId, t.number),
		index('feedback_project_path_idx').on(t.projectId, t.path),
		index('feedback_project_status_idx').on(t.projectId, t.status),
		index('feedback_created_idx').on(t.createdAt)
	]
);

export const comments = pgTable(
	'comments',
	{
		id: uuid('id').primaryKey().defaultRandom(),
		feedbackId: uuid('feedback_id')
			.notNull()
			.references(() => feedback.id, { onDelete: 'cascade' }),
		body: text('body').notNull(),
		authorName: text('author_name'),
		authorEmail: text('author_email'),
		userId: uuid('user_id').references(() => users.id, { onDelete: 'set null' }),
		...timestamps
	},
	(t) => [index('comments_feedback_idx').on(t.feedbackId)]
);

export const uploads = pgTable(
	'uploads',
	{
		id: uuid('id').primaryKey().defaultRandom(),
		projectId: uuid('project_id')
			.notNull()
			.references(() => projects.id, { onDelete: 'cascade' }),
		feedbackId: uuid('feedback_id').references(() => feedback.id, { onDelete: 'cascade' }),
		kind: text('kind').notNull().default('screenshot'),
		storageKey: text('storage_key').notNull(),
		mimeType: text('mime_type').notNull(),
		sizeBytes: integer('size_bytes').notNull(),
		width: integer('width'),
		height: integer('height'),
		createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow()
	},
	(t) => [index('uploads_feedback_idx').on(t.feedbackId)]
);

export type User = typeof users.$inferSelect;
export type Project = typeof projects.$inferSelect;
export type Session = typeof sessions.$inferSelect;
export type AuthRequest = typeof authRequests.$inferSelect;
export type Feedback = typeof feedback.$inferSelect;
export type NewFeedback = typeof feedback.$inferInsert;
export type Comment = typeof comments.$inferSelect;
export type Upload = typeof uploads.$inferSelect;
